Repository WildCodeSchool/0322_P3_Php_Lyon_Origins_Digital, pull requests merged in 2023-07, with the labels that each got.

#125 S03 us122 table viewed completement implémentée
  src/Controller/Admin/DashboardController.php
  src/Controller/Admin/TagCrudController.php
  src/Controller/DeleteController.php
  src/Entity/Viewed.php
  src/Repository/ViewedRepository.php
  src/Service/DeleteService.php
  tests/RoutingTest.php
Labels: Changes done

#129 S04 feat user comments fred
  assets/comment.js
  assets/displayViewCount.js
  assets/styles/app.scss
  config/services.yaml
  migrations/Version20230627132052.php
  src/Controller/CommentController.php
  src/Controller/VideoController.php
  src/Entity/Comment.php
  src/Entity/User.php
  src/Entity/Video.php
  src/Repository/CommentRepository.php
  templates/base.html.twig
  templates/shared/comment/add.html.twig
  templates/shared/comment/comment.html.twig
  templates/shared/comment/list.html.twig
  templates/video/show.html.twig
  tests/RoutingTest.php
  webpack.config.js
Labels: Changes done

#131 delete DOMParser
  assets/comment.js
Labels: Changes done

#127 add search by title name in modal input
  assets/navbar.js
  assets/searchVideos.js
  assets/styles/app.scss
  src/Controller/AjaxController.php
  src/Controller/VideoSearchController.php
  src/Repository/VideoRepository.php
  templates/base.html.twig
  templates/shared/navigation/desktop-navbar.html.twig
  templates/shared/navigation/mobile-navbar.html.twig
  templates/shared/search-modal.html.twig
  templates/video_search/search-result.html.twig
  webpack.config.js
Labels: Changes done

#133 S04 issue101 add filtered galleries
  assets/styles/app.scss
  composer.json
  composer.lock
  config/bundles.php
  src/Controller/VideoController.php
  src/Twig/Components/VideoGalleryComponent.php
  symfony.lock
  templates/components/VideoGalleryComponent.html.twig
  templates/home/index.html.twig
  templates/video/show.html.twig
Labels: Changes done

#136 improved user dashboard display
  templates/user/index.html.twig
Labels: Needs pair review

#137 add history to user dashboard
  src/Controller/UserController.php
  templates/user/index.html.twig
Labels: Needs pair review

#134 S04 issue99/105 header admin
  assets/styles/app.scss
  migrations/Version20230627134732.php
  src/Controller/Admin/VideoCrudController.php
  src/Controller/HomeController.php
  src/DataFixtures/VideoFixtures.php
  src/Entity/HeaderTrait.php
  src/Entity/Video.php
  templates/home/index.html.twig
Labels: Changes done

#135 S05 us creation securite
  migrations/Version20230705125607.php
  src/Controller/Admin/DashboardController.php
  src/Controller/Admin/UserCrudController.php
  src/Controller/DeleteController.php
  src/Controller/UploadController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  templates/base.html.twig
Labels: Needs pair review

#142 Header fix
  src/DataFixtures/VideoFixtures.php
Labels: Needs pair review

#148 S04 us bugs fix fred
  assets/displayViewCount.js
  src/Controller/Admin/UserCrudController.php
  src/Controller/RegistrationController.php
  src/Controller/UploadController.php
  src/Service/DeleteService.php
  src/Service/SaveVideoService.php
  src/Service/UploadService.php
  templates/login/index.html.twig
  templates/user/index.html.twig
Labels: Needs pair review

#150 Several display bug fixes
  assets/app.js
  assets/searchVideos.js
  templates/components/VideoGalleryComponent.html.twig
  templates/home/index.html.twig
  templates/shared/thumbnail/big-thumbnail.html.twig
  templates/user/index.html.twig
  templates/video/show.html.twig
Labels: Needs pair review

#151 S04 us custom actions in easy admin
  src/Controller/Admin/UserCrudController.php
  src/Controller/Admin/VideoCrudController.php
Labels: Needs pair review

#152 fix typo
  templates/video/show.html.twig
Labels: Needs pair review

#156 fix bug
  assets/styles/app.scss
  templates/home/index.html.twig
Labels: Needs pair review

#157 Update README.md
  README.md
Labels: Needs pair review

#159 change design for publication date
  src/Form/VideoType.php
  templates/registration/confirmation_email.html.twig
  templates/upload/index.html.twig
Labels: Needs pair review

#164 fix 'add comment' display on video/show
  templates/shared/comment/add.html.twig
Labels: Needs pair review

#165 fix 'add comment' button placement for loggedoff user
  templates/video/show.html.twig
Labels: Needs pair review

#166 pretty confirmation email
  assets/styles/email.css
  templates/registration/confirmation_email.html.twig
Labels: Needs pair review

#167 S05 issue 147 admin manage comments
  src/Controller/DeleteController.php
  src/Form/VideoType.php
  src/Service/DeleteService.php
  templates/shared/comment/comment.html.twig
  templates/video/show.html.twig
  tests/RoutingTest.php
Labels: Changes done

#170 Block access header
  assets/images/poster1-APEX.jpg
  src/Entity/HeaderTrait.php
  src/Entity/Video.php
Labels: Changes done

#171 S05 issue 100 userDashboard anchors
  assets/userDashboard.js
  templates/user/index.html.twig
  templates/video/show.html.twig
  webpack.config.js
Labels: Needs pair review

#173 add style to user dashboard header
  assets/avatar.js
  assets/styles/app.scss
  src/Form/AvatarType.php
  templates/shared/gallery/bt-gallery.html.twig
  templates/user/index.html.twig
  webpack.config.js
Labels: Changes done

#179 fix mobile navbar
  assets/styles/app.scss
  templates/shared/navigation/mobile-navbar.html.twig
Labels: Needs pair review

#183 change datetime on videoType form
  assets/styles/app.scss
  src/Controller/HomeController.php
  src/Controller/VideoController.php
  src/Form/VideoType.php
  src/Service/DeleteService.php
Labels: Needs pair review

#178 Fix bug
  assets/app.js
  assets/styles/app.scss
  src/Service/UploadService.php
  templates/home/index.html.twig
  templates/shared/comment/comment.html.twig
  templates/video/show.html.twig
Labels: Branch conflicts

#188 limit mostviewedvideo by date
  src/Repository/ViewedRepository.php
Labels: Needs pair review

#189 S05 issues 180 181 182
  assets/styles/app.scss
  templates/base.html.twig
  templates/shared/comment/comment.html.twig
  templates/user/index.html.twig
Labels: Needs pair review

#197 S05 issue 193 fixtures user
  assets/dropzone.js
  src/DataFixtures/CommentFixtures.php
  src/DataFixtures/UserFixtures.php
  src/DataFixtures/ViewedFixtures.php
  src/Repository/ViewedRepository.php
Labels: Needs pair review

#195 S06 issue192 contact page
  assets/navbar.js
  assets/styles/app.scss
  migrations/Version20230713121147.php
  src/Controller/Admin/ContactCrudController.php
  src/Controller/Admin/DashboardController.php
  src/Controller/ContactController.php
  src/Entity/Contact.php
  src/Entity/User.php
  src/Form/ContactType.php
  src/Repository/ContactRepository.php
  templates/base.html.twig
  templates/contact/index.html.twig
  templates/video/show.html.twig
Labels: Changes done

#204 delete towatch panel when no video in user towatch
  templates/video/show.html.twig
Labels: Changes done

#205 fix bug search videos
  src/Controller/VideoSearchController.php
Labels: Needs pair review

#206 pair bugfix1
  assets/comment.js
  assets/navbar.js
  src/Controller/CommentController.php
  src/DataFixtures/CommentFixtures.php
  src/Twig/Components/SmallVideoGalleryComponent.php
  templates/components/SmallVideoGalleryComponent.html.twig
  templates/home/index.html.twig
  templates/shared/comment/comment.html.twig
Labels: Needs pair review

#207 add favicon & fix trendingTags
  assets/favicon/gg-favicon-sm.png
  src/Controller/AjaxController.php
  src/Controller/HomeController.php
  templates/base.html.twig
  webpack.config.js
Labels: Needs pair review

#208 S07 translation of videos desc and titles
  src/DataFixtures/VideoFixtures.php
Labels: Needs pair review

#209 Add fixtures
  src/DataFixtures/UserFixtures.php
Labels: Needs pair review

#210 Add contact fixtures
  src/Controller/ContactController.php
  src/DataFixtures/ContactFixtures.php
Labels: Needs pair review
