Repository WildCodeSchool/0322_P3_Php_Lyon_Origins_Digital, pull requests merged in 2023-06, with the labels that each got.

#9 S01 us03 see more button
  assets/app.js
  assets/styles/app.scss
  composer.lock
  src/Repository/VideoRepository.php
  templates/video/index.html.twig
Labels: Changes done

#15 S01us05 issues fix
  assets/app.js
  assets/styles/app.scss
  src/Controller/HomeController.php
  src/Controller/VideoController.php
  templates/home/index.html.twig
  templates/shared/category-tag.html.twig
  templates/shared/gallery/bt-gallery.html.twig
  templates/shared/thumbnail/big-thumbnail.html.twig
  templates/shared/thumbnail/load-more.html.twig
  templates/shared/thumbnail/small-thumbnail.html.twig
  templates/video/index.html.twig
  templates/video/show.html.twig
  yarn.lock
Labels: Needs pair review

#22 display player
  assets/styles/app.scss
Labels: Changes done

#40 add click on any tag to access result of reseach by clicked tag
  assets/app.js
  src/Controller/SearchController.php
  templates/home/index.html.twig
  templates/search/index.html.twig
  templates/shared/category-tag.html.twig
  templates/shared/gallery/bt-gallery.html.twig
  templates/video/show.html.twig
Labels: Changes done

#43 fix username/description grid & fix favories width & fix title/hashta…
  assets/styles/app.scss
  src/DataFixtures/VideoFixtures.php
  templates/video/show.html.twig
Labels: Needs pair review

#45 fix overflowing text in bts
  assets/styles/app.scss
  src/DataFixtures/VideoFixtures.php
  templates/video/show.html.twig
Labels: Needs pair review

#49 trimmed openable desc on mobile
  assets/app.js
  templates/video/show.html.twig
Labels: Needs pair review

#53 fix bt sizing
  assets/styles/app.scss
  templates/shared/thumbnail/big-thumbnail.html.twig
Labels: Needs pair review

#57 fix bug see more
  assets/app.js
  templates/base.html.twig
Labels: Needs pair review

#76 S03 issues 70 64 58 56
  assets/app.js
  assets/styles/app.scss
  src/Controller/HomeController.php
  templates/home/index.html.twig
  templates/shared/gallery/bt-gallery.html.twig
  templates/shared/navbar-desktop.html.twig
  templates/shared/navbar-mobile.html.twig
  templates/shared/tag/category-tag.html.twig
  templates/shared/tag/tag-list.html.twig
  templates/video/show.html.twig
Labels: Needs pair review

#78 S03 issue 69 limit futur videos
  src/DataFixtures/VideoFixtures.php
  src/Repository/VideoRepository.php
Labels: Needs pair review

#79 S02 issue63 add more content
  assets/images/poster1-APEX.jpg
  assets/images/poster1-CS.jpg
  assets/images/poster1-FORTNITE.jpg
  assets/images/poster1-WOW.jpg
  assets/images/poster2-APEX.jpg
  assets/images/poster2-CS.jpg
  assets/images/poster2-FORTNITE.jpg
  assets/images/poster2-WOW.jpg
  assets/images/poster3-CS.jpg
  assets/images/poster3-FORTNITE.jpg
  src/DataFixtures/VideoFixtures.php
Labels: Needs pair review

#83 S03 us21 1 rajouter une date programmable a l uplaod des videos
  assets/addFav.js
  assets/addLater.js
  assets/addLike.js
  assets/plyr.js
  src/Entity/Video.php
  src/Form/VideoType.php
Labels: Needs pair review

#87 S03US62 add users dashboard
  assets/app.js
  assets/styles/app.scss
  migrations/Version20230621130052.php
  src/Controller/UserController.php
  src/Controller/VideoController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  templates/user/index.html.twig
  templates/video/show.html.twig
  tests/RoutingTest.php
Labels: Changes done

#104 S03 issue86 fix bug css
  assets/styles/app.scss
  templates/home/index.html.twig
  templates/shared/tag/tag-list.html.twig
Labels: Needs pair review

#116 fix several bugs
  composer.lock
  src/Controller/Admin/TagCrudController.php
  src/Controller/Admin/VideoCrudController.php
  src/Entity/User.php
  src/Form/RegistrationFormType.php
  templates/home/index.html.twig
  templates/registration/register.html.twig
  templates/search/index.html.twig
  templates/shared/tag/tag-list.html.twig
  templates/video/show.html.twig
Labels: Needs pair review

#123 S03 us122 add some querybuilders
  assets/addLike.js
  assets/displayViewCount.js
  config/packages/framework.yaml
  config/routes.yaml
  migrations/Version20230624132013.php
  migrations/Version20230625180327.php
  src/Controller/Admin/DashboardController.php
  src/Controller/Admin/VideoCrudController.php
  src/Controller/LikeController.php
  src/Controller/RegistrationController.php
  src/Controller/VideoController.php
  src/Controller/ViewedController.php
  src/DataFixtures/UserFixtures.php
  src/DataFixtures/ViewedFixtures.php
  src/Entity/User.php
  src/Entity/Video.php
  src/Entity/Viewed.php
  src/Form/VideoType.php
  src/Repository/ViewedRepository.php
  templates/admin/dashboard.html.twig
  templates/home/index.html.twig
  templates/search/index.html.twig
  templates/shared/thumbnail/big-thumbnail.html.twig
  templates/user/index.html.twig
  templates/video/show.html.twig
  tests/RoutingTest.php
  webpack.config.js
Labels: Needs pair review

#124 S04 create navbar
  assets/app.js
  assets/navbar.js
  assets/styles/app.scss
  templates/base.html.twig
  templates/home/index.html.twig
  templates/login/index.html.twig
  templates/registration/register.html.twig
  templates/search/index.html.twig
  templates/shared/navigation/desktop-navbar.html.twig
  templates/shared/navigation/mobile-navbar.html.twig
  templates/user/index.html.twig
  templates/video/show.html.twig
  webpack.config.js
Labels: Changes done, Needs pair review
